export const carriers = [
  {
    id: 1,
    name: "INS Vikrant",
    class: "Vikrant-class",
    country: "India",
    region: "Arabian Sea",
    status: "Active",
    lastUpdate: "16:42 UTC",
    lat: 15.2,
    lng: 72.4,
  },
  {
    id: 2,
    name: "USS Nimitz",
    class: "Nimitz-class",
    country: "United States",
    region: "Indian Ocean",
    status: "Active",
    lastUpdate: "16:38 UTC",
    lat: 12.0,
    lng: 65.0,
  },
  {
    id: 3,
    name: "Fujian",
    class: "Type 003",
    country: "China",
    region: "Taiwan Strait",
    status: "Active",
    lastUpdate: "16:40 UTC",
    lat: 21.5,
    lng: 118.0,
  },
];